import Head from 'next/head';
import { Inter } from '@next/font/google';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';
import { GetServerSideProps } from 'next';
import { fetchTweets } from '../utils/fetchTweets';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export default function Home({ tweets }: { tweets: Tweet[] }) {
  return (
    <div className='lg:max-w-6xl mx-auto max-h-screen overflow-hidden'>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster />
      <main className='grid grid-cols-9'>
        <Sidebar />
        <Feed tweets={tweets} />
        <Widgets />
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const tweets: Tweet[] = await fetchTweets();

  return {
    props: {
      tweets
    }
  }
}
